services:
  fog:
    build:
      context: ./..
      dockerfile: deployment/Dockerfile
    command: ["./fog-server"]

  cloud:
    build:
      context: ./..
      dockerfile: deployment/Dockerfile
    command: ["./cloud-server"]
