name: edge-cloud

services:
  dbeaver:
    image: dbeaver/cloudbeaver
    depends_on:
      - database
    restart: always
    ports:
      - "8978:8978"
    networks:
      - cloud

  database:
    image: postgres:16.0
    restart: always
    env_file:
      - ../../.cloud.env
    networks:
      - cloud
    ports:
      - "5432:5432"

  edge:
    container_name: edge
    image: codinggandalf/fog-computing:edge
    restart: always
    build:
      context: ./../..
      target: prod
      dockerfile: ./deployment/docker/Edge.Dockerfile
    env_file:
      - ../../.edge.env
    networks:
      - fog
      - cloud
    ports:
      - "5556:5556"

  cloud:
    container_name: cloud
    image: codinggandalf/fog-computing:cloud
    depends_on:
      - database
    build:
      context: ../..
      target: prod
      dockerfile: ./deployment/docker/Cloud.Dockerfile
    env_file:
      - ../../.cloud.env
    restart: always
    networks:
      - fog
      - cloud
    ports:
      - "5555:5555"

networks:
  fog:
    driver: bridge
  cloud:
    driver: bridge
