name: fog-cloud

services:
  dbeaver:
    image: dbeaver/cloudbeaver
    depends_on:
      - database
    restart: always
    ports:
      - "8978:8978"
    networks:
      - cloud

  database:
    image: postgres:16.0
    restart: always
    env_file:
      - ../../.cloud.env
    networks:
      - cloud
    ports:
      - "5432:5432"

  fog:
    container_name: fog
    image: fog
    restart: always
    depends_on:
      - cloud
    build:
      context: ./../..
      target: prod
      dockerfile: deployment/docker/Fog.Dockerfile
    env_file:
      - ../../.fog.env
      - ../../.env
    networks:
      - fog
      - cloud
    ports:
      - "5556:5556"

  cloud:
    container_name: cloud
    image: cloud
    depends_on:
      - database
    build:
      context: ./../..
      target: prod
      dockerfile: deployment/docker/Cloud.Dockerfile
    env_file:
      - ../../.cloud.env
      - ../../.env
    restart: always
    networks:
      - fog
      - cloud
    ports:
      - "5555:5555"

networks:
  fog:
    driver: bridge
  cloud:
    driver: bridge
