all:
  vars:
    ansible_ssh_private_key_file: /var/snap/multipass/common/data/multipassd/ssh-keys/id_rsa
    microk8s_version: 1.30/stable
    ansible_user: ubuntu

  children:
    microk8s_HA:
      hosts:
        microk8s-controller:

    microk8s_WORKERS:
      hosts:
        microk8s-node-1:
        microk8s-node-2:
        microk8s-node-3:
        microk8s-pi:

  hosts:
    microk8s-node-1:
      ansible_host: 10.105.227.38
    microk8s-node-2:
      ansible_host: 10.105.227.2
    microk8s-pi:
      ansible_host: 192.168.188.35
      ansible_user: pi
      ansible_ssh_private_key_file: ~/.ssh/ansible
    microk8s-controller:
      ansible_user: konsum-gandalf
      ansible_host: localhost
      ansible_connection: local
