all:
  vars:
    ansible_ssh_private_key_file: /var/snap/multipass/common/data/multipassd/ssh-keys/id_rsa
    microk8s_version: 1.30/stable
    ansible_user: ubuntu

  children:
    microk8s_HA:
      hosts:
        microk8s-controller:

    microk8s_WORKERS:
      hosts:
        microk8s-node1:
        microk8s-node2:

  hosts:
    microk8s-controller:
      ansible_host: 10.105.227.31
    microk8s-node1:
      ansible_host: 10.105.227.38
    microk8s-node2:
      ansible_host: 10.105.227.2
