apiVersion: v1
kind: ConfigMap
metadata:
  name: fog-config
  namespace: fog-cloud
data:
  NOTIFY_PORT: "5556"
  SEND_PORT: "5557"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: fog-cloud
data:
  POSTGRES_ADDR: "database:5432"
  POSTGRES_USER: "fog"
  POSTGRES_PASSWORD: "fog"
  POSTGRES_DB: "fog"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: fog-cloud
data:
  SOCKET_ADDR: "cloud:5555"
