apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: fog-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - cloud
      containers:
        - name: postgres
          image: postgres:16.0
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: cloud-config
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: fog-cloud
spec:
  type: LoadBalancer
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
