apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbeaver
  namespace: fog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbeaver
  template:
    metadata:
      labels:
        app: dbeaver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - cloud
      containers:
        - name: dbeaver
          image: dbeaver/cloudbeaver
          ports:
            - containerPort: 8978
          envFrom:
            - configMapRef:
                name: cloud-config
---
apiVersion: v1
kind: Service
metadata:
  name: dbeaver
  namespace: fog
spec:
  type: LoadBalancer
  selector:
    app: dbeaver
  ports:
    - protocol: TCP
      port: 8978
      targetPort: 8978
