apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog
  namespace: edge
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fog
  template:
    metadata:
      labels:
        app: fog
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - edge
                      - edge
      containers:
        - name: edge
          image: codinggandalf/fog-computing:edge
          ports:
            - containerPort: 5556
          envFrom:
            - configMapRef:
                name: fog-config
            - configMapRef:
                name: config
---
apiVersion: v1
kind: Service
metadata:
  name: fog
  namespace: edge
spec:
  selector:
    app: fog
  ports:
    - protocol: TCP
      port: 5556
      targetPort: 5556
