- name: Remove nodes from MicroK8s cluster
  hosts: all
  become: yes

- hosts: all
  roles:
    - role: 'istvano.microk8s'
      vars:
        microk8s_plugins:
          dns: "1.1.1.1"
          ingress: true
          metrics-server: false
          cert-manager: true
          openebs: true
          portainer: true
          helm3: true

- name: Create Kubernetes namespace
  hosts: microk8s-controller
  become: yes
  tasks:
    - name: Create fog-cloud namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: fog-cloud
        state: present